name: Download and Print GCC Unicode Header

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Update packages
        run: sudo apt-get update
  
      - name: Install latest GCC
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          apt-cache search gcc | grep gcc-
          sudo apt-get install gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 60 --slave /usr/bin/g++ g++ /usr/bin/g++-14
          gcc --version
        
      - name: Find GCC include path and print unicode.h
        run: |
          cat /usr/include/bits/unicode.h

