name: Download and Print GCC Unicode Header

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Update packages
        run: sudo apt-get update
  
      - name: Install latest GCC
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install gcc-14 g++-14
          gcc-14 --version
        
      - name: Find GCC include path and print unicode.h
        run: |
          cat /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/unicode.h

