name: Download and Print GCC Unicode Header

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Update packages
        run: sudo apt-get update
  
      - name: Install latest GCC
        run: |
          sudo apt-get install -y gcc
          gcc --version
        
